// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB16-KmfmViAXDzPabD-xrh2x0ULbFXR_s',
    appId: '1:576567884672:web:7c70270a97f1e49f4c9f65',
    messagingSenderId: '576567884672',
    projectId: 'cloud-c03c8',
    authDomain: 'cloud-c03c8.firebaseapp.com',
    databaseURL: 'https://cloud-c03c8-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-c03c8.firebasestorage.app',
    measurementId: 'G-Y7357VNRS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-PvPwUD_iN27QT88iEQIuLZoTYsR2dwE',
    appId: '1:576567884672:android:77e877cf6f4dc3904c9f65',
    messagingSenderId: '576567884672',
    projectId: 'cloud-c03c8',
    databaseURL: 'https://cloud-c03c8-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-c03c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6gi9CD9_jDiQ1dBVNQgW6ZNaAZKqGUaU',
    appId: '1:576567884672:ios:31dfe96217b42bb14c9f65',
    messagingSenderId: '576567884672',
    projectId: 'cloud-c03c8',
    databaseURL: 'https://cloud-c03c8-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-c03c8.firebasestorage.app',
    iosClientId: '576567884672-prqttqic85d3vlfq8qp3cv5no7vnl8ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudtask2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6gi9CD9_jDiQ1dBVNQgW6ZNaAZKqGUaU',
    appId: '1:576567884672:ios:31dfe96217b42bb14c9f65',
    messagingSenderId: '576567884672',
    projectId: 'cloud-c03c8',
    databaseURL: 'https://cloud-c03c8-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-c03c8.firebasestorage.app',
    iosClientId: '576567884672-prqttqic85d3vlfq8qp3cv5no7vnl8ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudtask2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB16-KmfmViAXDzPabD-xrh2x0ULbFXR_s',
    appId: '1:576567884672:web:d8b293a7b02759754c9f65',
    messagingSenderId: '576567884672',
    projectId: 'cloud-c03c8',
    authDomain: 'cloud-c03c8.firebaseapp.com',
    databaseURL: 'https://cloud-c03c8-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-c03c8.firebasestorage.app',
    measurementId: 'G-XSTT64FRT0',
  );

}